version: '3'

services:
  scimgateway:
    build: ./scimgateway
    ports:
      - "8881:8881"
      - "888:888"
    restart: always
    environment:
      loki-new-connector1111111111_BASIC_0_USERNAME: a
      loki-new-connector1111111111_BASIC_0_PASSWORD: a
      ldap-new-connector_BASIC_0_USERNAME: rai123
      ldap-new-connector_BASIC_0_PASSWORD: rai123
      username: luciana
    volumes:
      - data:/home/node/app/data
   
  forms:
    depends_on:
      - scimgateway
    build: ./forms
    ports:
      - "8000:80"
    restart: always
  
  gateway:
      depends_on:
      - scimgateway
      build: ./gateway
      ports:
        - "5000:5000"
      restart: always   

volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/luciana/Documents/qscim-files/temp/data